# Generated by Django 5.1.2 on 2024-10-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task',
        ),
    ]
